In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

In [15]:
a = np.array([1,2,3,4,5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
b = np.array([[10,20,30], [40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [12]:
d = np.arange(1, 35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [13]:
a * 10

array([10, 20, 30, 40, 50])

In [16]:
c + a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [17]:
c - a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [18]:
c * a

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

In [19]:
c / a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

In [20]:
c % a

array([0.22, 0.97, 2.77, 2.72, 0.55, 4.  ])

In [22]:
aa = np.array([[1,2,3],[4,5,6], [7,8,9]])
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
bb = np.array([[0,12,13],[41,15,16], [17,18,19]])
bb

array([[ 0, 12, 13],
       [41, 15, 16],
       [17, 18, 19]])

In [24]:
aa * bb

array([[  0,  24,  39],
       [164,  75,  96],
       [119, 144, 171]])

In [25]:
np.dot(aa, bb)

array([[133,  96, 102],
       [307, 231, 246],
       [481, 366, 390]])